export const FETCH_STORES_DATA_START = 'FETCH_STORES_DATA_START';
export const FETCH_STORES_DATA_SUCESS = 'FETCH_STORES_DATA_SUCESS';
export const FETCH_STORES_DATA_FAILURE = 'FETCH_STORES_DATA_FAILURE';